name: Verify order
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
jobs:
  order:
    name: order communities.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Order json by keys
        run: jq -S . communities.json > sorted_communities.json
      - name: Verfy commited json is ordered
        run: diff communities.json sorted_communities.json
